trigger:
  - stable-2.12

pr:
  - stable-2.12

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: docker build -t ansible-core-test-container .
    displayName: Build Container
  - script: docker history ansible-core-test-container
    displayName: Show History
